# import libraries

In [2]:
import pandas as pd
import numpy as np

# read csv data

In [3]:
auto_df=pd.read_csv('C:/Users/tech2k8/Documents/automobile data set.txt')
auto_df.head(10) #auto_df.tail(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

# write and save data

In [4]:
auto_df.to_excel('auto_df new.xlsx',sheet_name='auto',index='false')

# data types of the data set

In [10]:
auto_df.dtypes
#auto_df.shape

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

# Statistics of the data set

In [7]:
auto_df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

# index and slicing

In [8]:
#all columns view
auto_df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [9]:
#particular row view

#auto_df[2:5] 
#auto_df.loc[2:5]
auto_df.iloc[2:5]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [10]:
#particular column view

auto_df['highway-mpg']

0      27
1      27
2      26
3      30
4      22
       ..
200    28
201    25
202    23
203    27
204    25
Name: highway-mpg, Length: 205, dtype: int64

In [11]:
#type identification
type(auto_df['highway-mpg'])

pandas.core.series.Series

# descriptive statistics

In [12]:
print(auto_df['highway-mpg'].mean())
print(auto_df['highway-mpg'].max())
print(auto_df['highway-mpg'].min())
print(auto_df['highway-mpg'].median())
print(auto_df['highway-mpg'].mode())
print(auto_df['highway-mpg'].var())
print(auto_df['highway-mpg'].std())

30.75121951219512
54
16
30.0
0    25
dtype: int64
47.42309899569578
6.88644313094182

# set and reset index

In [13]:
auto_df.set_index('price')

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
price,,,,,,,,,,,,,,,,,,,,,
13495,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
16500,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
16500,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
13950,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
17450,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16845,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28
19045,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25
21485,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23
22470,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,six,145,idi,3.01,3.40,23.0,106,4800,26,27
22625,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25

In [14]:
auto_df.reset_index (inplace=True)

# column addition and deletion

In [15]:

auto_df['addition column']=pd.Series(np.arange(1,206))
auto_df.tail()

,index,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,addition column
200,200,-1,95,volvo,gas,std,four,sedan,rwd,front,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845,201
201,201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045,202
202,202,-1,95,volvo,gas,std,four,sedan,rwd,front,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485,203
203,203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,...,idi,3.01,3.40,23.0,106,4800,26,27,22470,204
204,204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625,205

In [16]:
del auto_df['addition column']
#auto_df.pop('addition column')
auto_df.head()

,index,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,3,2,164,audi,gas,std,four,sedan,fwd,front,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,4,2,164,audi,gas,std,four,sedan,4wd,front,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

# row addition and deletion

In [26]:
df=pd.DataFrame([1,2],columns=['aspiration'],index=['a','b'])
new_auto_df=auto_df.append(df)
new_auto_df

,aspiration,body-style,bore,city-mpg,compression-ratio,curb-weight,drive-wheels,engine-location,engine-size,engine-type,...,make,normalized-losses,num-of-cylinders,num-of-doors,peak-rpm,price,stroke,symboling,wheel-base,width
0,std,convertible,3.47,21.0,9.0,2548.0,rwd,front,130.0,dohc,...,alfa-romero,?,four,two,5000,13495,2.68,3.0,88.6,64.1
1,std,convertible,3.47,21.0,9.0,2548.0,rwd,front,130.0,dohc,...,alfa-romero,?,four,two,5000,16500,2.68,3.0,88.6,64.1
2,std,hatchback,2.68,19.0,9.0,2823.0,rwd,front,152.0,ohcv,...,alfa-romero,?,six,two,5000,16500,3.47,1.0,94.5,65.5
3,std,sedan,3.19,24.0,10.0,2337.0,fwd,front,109.0,ohc,...,audi,164,four,four,5500,13950,3.40,2.0,99.8,66.2
4,std,sedan,3.19,18.0,8.0,2824.0,4wd,front,136.0,ohc,...,audi,164,five,four,5500,17450,3.40,2.0,99.4,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,std,sedan,3.58,18.0,8.8,3012.0,rwd,front,173.0,ohcv,...,volvo,95,six,four,5500,21485,2.87,-1.0,109.1,68.9
203,turbo,sedan,3.01,26.0,23.0,3217.0,rwd,front,145.0,ohc,...,volvo,95,six,four,4800,22470,3.40,-1.0,109.1,68.9
204,turbo,sedan,3.78,19.0,9.5,3062.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5400,22625,3.15,-1.0,109.1,68.9
a,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
auto_df=new_auto_df.drop(['a','b'])
auto_df

,aspiration,body-style,bore,city-mpg,compression-ratio,curb-weight,drive-wheels,engine-location,engine-size,engine-type,...,make,normalized-losses,num-of-cylinders,num-of-doors,peak-rpm,price,stroke,symboling,wheel-base,width
0,std,convertible,3.47,21.0,9.0,2548.0,rwd,front,130.0,dohc,...,alfa-romero,?,four,two,5000,13495,2.68,3.0,88.6,64.1
1,std,convertible,3.47,21.0,9.0,2548.0,rwd,front,130.0,dohc,...,alfa-romero,?,four,two,5000,16500,2.68,3.0,88.6,64.1
2,std,hatchback,2.68,19.0,9.0,2823.0,rwd,front,152.0,ohcv,...,alfa-romero,?,six,two,5000,16500,3.47,1.0,94.5,65.5
3,std,sedan,3.19,24.0,10.0,2337.0,fwd,front,109.0,ohc,...,audi,164,four,four,5500,13950,3.40,2.0,99.8,66.2
4,std,sedan,3.19,18.0,8.0,2824.0,4wd,front,136.0,ohc,...,audi,164,five,four,5500,17450,3.40,2.0,99.4,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,std,sedan,3.78,23.0,9.5,2952.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5400,16845,3.15,-1.0,109.1,68.9
201,turbo,sedan,3.78,19.0,8.7,3049.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5300,19045,3.15,-1.0,109.1,68.8
202,std,sedan,3.58,18.0,8.8,3012.0,rwd,front,173.0,ohcv,...,volvo,95,six,four,5500,21485,2.87,-1.0,109.1,68.9
203,turbo,sedan,3.01,26.0,23.0,3217.0,rwd,front,145.0,ohc,...,volvo,95,six,four,4800,22470,3.40,-1.0,109.1,68.9
204,turbo,sedan,3.78,19.0,9.5,3062.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5400,22625,3.15,-1.0,109.1,68.9

# particular value access

In [21]:
auto_df[auto_df['price']>='16500']

,aspiration,body-style,bore,city-mpg,compression-ratio,curb-weight,drive-wheels,engine-location,engine-size,engine-type,...,make,normalized-losses,num-of-cylinders,num-of-doors,peak-rpm,price,stroke,symboling,wheel-base,width
1,std,convertible,3.47,21.0,9.0,2548.0,rwd,front,130.0,dohc,...,alfa-romero,?,four,two,5000,16500,2.68,3.0,88.6,64.1
2,std,hatchback,2.68,19.0,9.0,2823.0,rwd,front,152.0,ohcv,...,alfa-romero,?,six,two,5000,16500,3.47,1.0,94.5,65.5
4,std,sedan,3.19,18.0,8.0,2824.0,4wd,front,136.0,ohc,...,audi,164,five,four,5500,17450,3.40,2.0,99.4,66.4
6,std,sedan,3.19,19.0,8.5,2844.0,fwd,front,136.0,ohc,...,audi,158,five,four,5500,17710,3.40,1.0,105.8,71.4
7,std,wagon,3.19,19.0,8.5,2954.0,fwd,front,136.0,ohc,...,audi,?,five,four,5500,18920,3.40,1.0,105.8,71.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,std,sedan,3.78,23.0,9.5,2952.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5400,16845,3.15,-1.0,109.1,68.9
201,turbo,sedan,3.78,19.0,8.7,3049.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5300,19045,3.15,-1.0,109.1,68.8
202,std,sedan,3.58,18.0,8.8,3012.0,rwd,front,173.0,ohcv,...,volvo,95,six,four,5500,21485,2.87,-1.0,109.1,68.9
203,turbo,sedan,3.01,26.0,23.0,3217.0,rwd,front,145.0,ohc,...,volvo,95,six,four,4800,22470,3.40,-1.0,109.1,68.9
204,turbo,sedan,3.78,19.0,9.5,3062.0,rwd,front,141.0,ohc,...,volvo,95,four,four,5400,22625,3.15,-1.0,109.1,68.9

In [22]:
auto_df[auto_df['price']==auto_df['price'].min()]

,aspiration,body-style,bore,city-mpg,compression-ratio,curb-weight,drive-wheels,engine-location,engine-size,engine-type,...,make,normalized-losses,num-of-cylinders,num-of-doors,peak-rpm,price,stroke,symboling,wheel-base,width
147,std,wagon,3.62,25.0,9.0,2455.0,fwd,front,108.0,ohcf,...,subaru,89,four,four,5200,10198,2.64,0.0,97.0,65.4

In [23]:
auto_df[['make','price']][auto_df['price']==auto_df['price'].min()]

       make  price
147  subaru  10198

In [24]:
auto_df[['make']][auto_df['make']=='volvo']

      make
194  volvo
195  volvo
196  volvo
197  volvo
198  volvo
199  volvo
200  volvo
201  volvo
202  volvo
203  volvo
204  volvo